--- 
    environment: production
    chdir: /Users/anayden/Documents/projects/habr
    pid: /Users/anayden/Documents/projects/habr/tmp/thin.pid 
    rackup: /Users/anayden/Documents/projects/habr/config/config.ru 
    log: /Users/anayden/Documents/projects/habr/log/thin.log 
    max_conns: 1024 
    timeout: 30 
    max_persistent_conns: 512 
    daemonize: true